nginx:
  image: fink3l/nginx:latest
  ports:
    - 80:80
  volumes:
    - ./.datadir/nginx/conf.d:/etc/nginx/conf.d
  volumes_from:
    - fpm:rw
  environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
  links:
    - fpm

fpm:
  image: fink3l/fpm:latest
  volumes:
    - ./:/usr/share/nginx/html:rw
    - /usr/share/nginx/html/.datadir/
    - .datadir/fpm/php.ini:/usr/local/etc/php/php.ini
  links:
    - postgres

postgres:
  image: postgres:latest
  ports:
    - 5434:5432
  volumes:
    - ./.datadir/postgres:/data/postgres
  environment:
    POSTGRES_PASSWORD: 123 
    POSTGRES_USER: postgres
    PGDATA : /data/postgres

composer:
  image: composer/composer:php7
  command: install
  working_dir: /usr/share/nginx/html
  volumes_from:
    - fpm:rw
  links:
    - fpm
